import {offset} from './data';
export type Discussion={id:string;owner:string;name:string;title:string;body:string;category:string;created:string;archived?:boolean};
export type Comment={id:string;post:string;owner:string;name:string;body:string;created:string};
export type ChatMessage={id:string;thread:string;sender:string;name:string;body:string;created:string};
export type Relationship={id:string;owner:string;name:string;company:string;sector:string;region:string;kind:string;year:string;context:string;looking:string;intro:boolean;shared:boolean;consent:boolean;archived?:boolean};
export type IntroRequest={id:string;relationship:string;from:string;to:string;name:string;target:string;message:string;status:string;reply?:string;created:string};
export type WorkflowData={viewerId:string;posts:Discussion[];comments:Comment[];messages:ChatMessage[];registerEnabled:boolean;relationships:Relationship[];intros:IntroRequest[]};
export const emptyWorkflows:WorkflowData={viewerId:'',posts:[],comments:[],messages:[],registerEnabled:false,relationships:[],intros:[]};
export function demoWorkflows():WorkflowData{return {viewerId:'demo-self',posts:[{id:'demo-post1',owner:'demo-lena',name:'Lena W.',category:'Learning',title:'Ein Satz weniger. Ein besseres Gespräch.',body:'Ich habe heute meine Vorstellung auf zwei Sätze gekürzt und danach wirklich gewartet. Mein Learning: Die erste Pause nicht sofort mit einem weiteren Argument füllen. Was hilft euch dabei, mehr zuzuhören?',created:offset(-1)+'T14:15:00Z'},{id:'demo-post2',owner:'demo-sophie',name:'Sophie R.',category:'Feedback',title:'Wer übt mit mir den Einwand „kein Bedarf“?',body:'Ich würde gern zwei Gesprächsvarianten durchspielen und danach Feedback zu meinen Fragen bekommen. Zehn Minuten reichen schon. Wer hat diese Woche Lust?',created:offset(0)+'T08:00:00Z'}],comments:[{id:'demo-comment1',post:'demo-post1',owner:'demo-malik',name:'Malik K.',body:'Ich notiere mir vor dem Call eine offene Frage. Das erinnert mich daran, erst einmal zuzuhören.',created:offset(-1)+'T15:10:00Z'}],messages:[],registerEnabled:true,relationships:[{id:'demo-rel1',owner:'demo-lena',name:'Lena W.',company:'Beispielbetrieb Nordwerk',sector:'Handwerk',region:'NRW',kind:'Kundenprojekt',year:'2025',context:'Fiktives Recruiting-Projekt für einen Handwerksbetrieb. Gemeinsame Abstimmung zur Bewerberansprache und zu internen Abläufen.',looking:'Austausch über Recruiting-Prozesse und Automatisierung.',intro:true,shared:true,consent:true},{id:'demo-rel2',owner:'demo-malik',name:'Malik K.',company:'Beispielberatung Klarblick',sector:'Beratung',region:'DACH',kind:'Kooperation',year:'2026',context:'Fiktive Zusammenarbeit an einer neuen Website und einer verständlicheren Darstellung des Angebots.',looking:'Partner mit Erfahrung in B2B-Terminvereinbarung.',intro:true,shared:true,consent:true},{id:'demo-rel3',owner:'demo-self',name:'Alex',company:'Mein Beispielpartner',sector:'B2B-Software',region:'DACH',kind:'Empfehlung',year:'2026',context:'Ein eigener fiktiver Eintrag, an dem du Bearbeiten, Freigeben und Archivieren ausprobieren kannst.',looking:'Erfahrung mit CRM-Einführung.',intro:false,shared:false,consent:false}],intros:[]}}
